# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\"?\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\"@\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x14\n\x06\x42ookId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x16\n\x08MemberId\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\rBorrowRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x05\"3\n\rReturnRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x11\n\tmember_id\x18\x02 \x01(\x05\"e\n\tBorrowing\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tmember_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x62ook_id\x18\x03 \x01(\x05\x12\x13\n\x0b\x62orrow_date\x18\x04 \x01(\t\x12\x13\n\x0breturn_date\x18\x05 \x01(\t\"(\n\x08\x42ookList\x12\x1c\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\r.library.Book\".\n\nMemberList\x12 \n\x07members\x18\x01 \x03(\x0b\x32\x0f.library.Member\"7\n\rBorrowingList\x12&\n\nborrowings\x18\x01 \x03(\x0b\x32\x12.library.Borrowing\"\x07\n\x05\x45mpty2\xc6\x04\n\x0eLibraryService\x12,\n\nCreateBook\x12\r.library.Book\x1a\x0f.library.BookId\x12*\n\nUpdateBook\x12\r.library.Book\x1a\r.library.Book\x12)\n\x07GetBook\x12\x0f.library.BookId\x1a\r.library.Book\x12\x32\n\x0c\x43reateMember\x12\x0f.library.Member\x1a\x11.library.MemberId\x12\x30\n\x0cUpdateMember\x12\x0f.library.Member\x1a\x0f.library.Member\x12/\n\tGetMember\x12\x11.library.MemberId\x1a\x0f.library.Member\x12\x38\n\nBorrowBook\x12\x16.library.BorrowRequest\x1a\x12.library.Borrowing\x12\x38\n\nReturnBook\x12\x16.library.ReturnRequest\x1a\x12.library.Borrowing\x12.\n\tListBooks\x12\x0e.library.Empty\x1a\x11.library.BookList\x12\x32\n\x0bListMembers\x12\x0e.library.Empty\x1a\x13.library.MemberList\x12@\n\x13GetMemberBorrowings\x12\x11.library.MemberId\x1a\x16.library.BorrowingListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=26
  _globals['_BOOK']._serialized_end=89
  _globals['_MEMBER']._serialized_start=91
  _globals['_MEMBER']._serialized_end=155
  _globals['_BOOKID']._serialized_start=157
  _globals['_BOOKID']._serialized_end=177
  _globals['_MEMBERID']._serialized_start=179
  _globals['_MEMBERID']._serialized_end=201
  _globals['_BORROWREQUEST']._serialized_start=203
  _globals['_BORROWREQUEST']._serialized_end=254
  _globals['_RETURNREQUEST']._serialized_start=256
  _globals['_RETURNREQUEST']._serialized_end=307
  _globals['_BORROWING']._serialized_start=309
  _globals['_BORROWING']._serialized_end=410
  _globals['_BOOKLIST']._serialized_start=412
  _globals['_BOOKLIST']._serialized_end=452
  _globals['_MEMBERLIST']._serialized_start=454
  _globals['_MEMBERLIST']._serialized_end=500
  _globals['_BORROWINGLIST']._serialized_start=502
  _globals['_BORROWINGLIST']._serialized_end=557
  _globals['_EMPTY']._serialized_start=559
  _globals['_EMPTY']._serialized_end=566
  _globals['_LIBRARYSERVICE']._serialized_start=569
  _globals['_LIBRARYSERVICE']._serialized_end=1151
# @@protoc_insertion_point(module_scope)
